version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

install:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          # Build/Package for production
          $env:DEPLOY_ENVIRONMENT="prod"
      } else {
          # Build/Package for staging
          $env:DEPLOY_ENVIRONMENT="staging"
      }
  - ps: Write-Host "$env:DEPLOY_ENVIRONMENT build"
  - ps: Copy-Item -Path ".\$env:DEPLOY_ENVIRONMENT.txt" -Destination ".\BuildArtifact.txt"

build: off

artifacts:
  - path: BuildArtifact.txt
    name: BuildArtifact

before_deploy: # Only run for staging builds
  - ps: Write-Host "Running before_deploy for staging build..."

deploy: # Only run for staging builds
  - provider: Environment
    name: appveyor-deploy-test-staging
    on:
      branch: master
      appveyor_repo_tag: false

after_deploy: # Only run for staging builds
  - ps: Write-Host "Running after_deploy for staging build..."

on_success:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          # Only run for production builds
          Write-Host "Deploying to production..."
      }

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 5tB2yxNNtAeh5Qf6ElBKvUIJrRLitCLrmN82qnHGp5iRoQGud71J/EsiFy7zF61Uj18acJtOxV6dLTy+ZR95koi71iKkwNev7iLUuEmbgLE=