version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          # Build/Package for production
          $env:DEPLOY_ENVIRONMENT="prod"
      } else {
          # Build/Package for staging
          $env:DEPLOY_ENVIRONMENT="staging"
      }
  - ps: Write-Host "$env:DEPLOY_ENVIRONMENT build"

install:
  - ps: Copy-Item -Path ".\$env:DEPLOY_ENVIRONMENT.txt" -Destination ".\BuildArtifact.txt"

build: off

artifacts:
  - path: BuildArtifact.txt
    name: BuildArtifact

deploy:
  - provider: Environment
    name: appveyor-deploy-test-staging
    on:
      DEPLOY_ENVIRONMENT: staging
  - provider: Environment
    name: appveyor-deploy-test-prod
    on:
      DEPLOY_ENVIRONMENT: prod

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 5tB2yxNNtAeh5Qf6ElBKvUIJrRLitCLrmN82qnHGp5iRoQGud71J/EsiFy7zF61Uj18acJtOxV6dLTy+ZR95koi71iKkwNev7iLUuEmbgLE=